services:
  zarr_neuroglancer:
    container_name: zarr_neuroglancer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "7000:7000"
    volumes:
      - "D:/iansaididontcare/Lab/zarr_and_neuroglancer/code:/workspace/code"
      - "D:/iansaididontcare/Lab/others/YA_HAN:/workspace/data"
    working_dir: /workspace
    command: uvicorn code.server:app --host 0.0.0.0 --port 8000
